version: '3.9'
services:
  ms-sql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "!P@ssw0rdx1x2x3x4x5"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
  doofast2.0:
    build: .
    depends_on:
      - ms-sql-server
    ports:
      - "8080:80"